# Generated by Django 4.0.5 on 2022-06-04 10:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catrgory',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
