# Generated by Django 4.0.5 on 2022-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_delete_catrgory_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('tanks', 'Танки'), ('helt', 'Хилы'), ('dd', 'ДД'), ('dealer', 'Торговцы'), ('guildmaster', 'Гилдмастеры'), ('questgiver', 'Квестгиверы'), ('blacksmith', 'Кузнецы'), ('tanner', 'Кожевенники'), ('potions', 'Зельевары'), ('spell', 'Мастера Заклинаний')], max_length=255),
        ),
    ]
